- deployment/modules/cloudflare/account/redirects.tf
> fix: only one ruleset of each type with multiple rules

- deployment/modules/cloudflare/account/pages-project.tf
[chore: remove immich-app cloudflare pages project](https://github.com/immich-app/devtools/pull/65/commits/5a8975f8c4f0520b8de4dc8b667a2ee0b33afdab)
[5a8975f](https://github.com/immich-app/devtools/pull/65/commits/5a8975f8c4f0520b8de4dc8b667a2ee0b33afdab)
[chore: tofu ignore changes to cloudflare pages web analytics](https://github.com/immich-app/devtools/pull/65/commits/90504b172c5678c077cfbdd44685c730f790c3fb)
> chore: remove immich-app cloudflare pages project

- deployment/modules/github/org/.terraform.lock.hcl
- deployment/modules/github/org/config.tf
- deployment/modules/github/org/providers.tf
- deployment/modules/github/org/repo-files/.editorconfig
- deployment/modules/github/org/repo-files/CODE_OF_CONDUCT.md
- deployment/modules/github/org/repo-files/LICENSE
- deployment/modules/github/org/repo-files/SECURITY.md
- deployment/modules/github/org/repositories.tf
- deployment/modules/github/org/terragrunt.hcl
- deployment/modules/github/org/webhooks.tf
With this, we now control creation and management of repositories with IaC. This includes the creation of the repo, creation of our default rulesets for main protection and creation of some default files we should have everywhere
> feat: github repository IaC

- deployment/modules/github/org/repositories-temp-rename.tf
- deployment/modules/github/org/repositories.tf
I went the route of renaming the repo within github then re-importing it into tofu
> chore: rename my.immich.app repo to static-pages

- kubernetes/apps/pipelines/geocoding/database/app/database.yaml
> fix: Drop invalid parameters

- renovate.json
This has renovate set the PRs to automerge so they merge immediately after approval
> feat: Enable automerge for renovate PRs

- deployment/modules/cloudflare/account/redirects.tf
> fix: add redirect for www.immich.app

- kubernetes/apps/monitoring/grafana/app/grafana.yaml
> fix: grafana fs permissions, instance label

- deployment/modules/github/org/repositories.tf
Placeholder for future `@immich/ui` svelte web component npm package.
> chore: repository for  npm package

- deployment/modules/1password/account/k8s-secrets.tf
- kubernetes/apps/authentication/dexidp/app/helmrelease.yaml
- kubernetes/apps/tools/outline/app/helmrelease.yaml
> chore: final outline fixes

- kubernetes/apps/monitoring-dev/victoria-metrics/ingress/kustomization.yaml
- kubernetes/apps/monitoring/victoria-metrics/ingress/kustomization.yaml
> fix: actually include new vm admin token

- tf/deployment/modules/cloudflare/account/redirects.tf
Add the following redirections
- `https://get.immich.app/android` -> play store
- `https://get.immich.app/ios` -> app store
- `https://get.immich.app/fdroid` -> f-droid
> feat: app redirects

- tf/deployment/modules/cloudflare/account/redirects.tf
> fix: android path matching

- kubernetes/apps/preview/github-prs/app/resource-set.yaml
- kubernetes/apps/preview/github-prs/app/rsip.yaml
> fix: preview namespace name

- kubernetes/apps/preview/github-prs/app/resource-set.yaml
- kubernetes/apps/preview/github-prs/app/rsip.yaml
A little bit fiddly with the templating, but this way it should also get the nice automatic updating based on commit hash.
> feat: preview env for main branch

- kubernetes/apps/preview/github-prs/app/resource-set.yaml
The previous one worked in the test playground...
> fix: map key presence check

- kubernetes/apps/preview/github-previews/app/resource-set.yaml
Cause the regex expects quotes :facepalm:
> fix: quote release version for renovate

- kubernetes/apps/preview/github-previews/app/resource-set.yaml
I should investigate why renovate won't pick this up :(
> chore: bump chart version

- kubernetes/apps/preview/kustomization.yaml
How do I keep missing this :facepalm:
> fix: actually include demo manifests

- tf/deployment/modules/scoped/discord/community/roles.tf
- tf/deployment/modules/scoped/monitoring/grafana/terragrunt.hcl
add dependency from grafana -> discord
> fix: re-add removed everyone permission

- kubernetes/apps/infrastructure/networking/ingress-nginx/app/helmrelease.yaml
> fix: use updateStrategy Recreate for ingress-nginx

- kubernetes/flux/config/flux.yaml
I'm hoping this way renovate manages to update them together
> chore: set flux tag in comment after digest

- kubernetes/README.MD
This place is not a place of honor, no highly esteemed deed is commemorated here, etc
> chore: add secrets bootstrap warning

- kubernetes/apps/monitoring-dev/grafana/app/grafana.yaml
- kubernetes/apps/monitoring-dev/grafana/ks.yaml
> fix: quotes substitution

- kubernetes/apps/authentication/zitadel/app/helmrelease.yaml
- kubernetes/flux/repositories/helm/zitadel.yaml
> chore: revert back to upstream zitadel chart 

- containers/actions-runner/Dockerfile
Reverts immich-app/devtools#795
> chore: revert "fix: accept android-sdk licenses"

- kubernetes/apps/infrastructure/secrets/onepassword/app/helmrelease.yaml
Reverts immich-app/devtools#803
Because of https://github.com/1Password/onepassword-operator/issues/209
> chore: revert "chore(deps): update helm release connect to v2"

- .mise/config.toml
this lets it give shell completions for tasks
> chore: add usage cli to mise

- .github/workflows/terragrunt.yaml
> chore: pin use-mise action to tag

- kubernetes/apps/monitoring/grafana/app/datasource.yaml
I swear I'd set it right locally, no idea where that went
> fix: set correct vlogs datasource address

- tf/deployment/modules/scoped/discord/community/channels.tf
#team-voice-2 electric boogaloo
> feat: team-voice-2 channel

- tf/deployment/modules/scoped/discord/community/channels.tf
Now we will have two team voice channels, make the main one high bitrate
> feat: team voice high bitrate

- tf/deployment/modules/shared/github/webhooks/webhooks.tf
Counterpart to https://github.com/immich-app/discord-bot/pull/354
> feat: add worflow_run to bot webhooks

- actions/pre-job/action.yml
Needed for https://github.com/immich-app/base-images/blob/main/.github/workflows/build-server-base.yml to trigger based on the ref.
> feat: custom force input for pre-job

- kubernetes/apps/infrastructure/operators/victoria-metrics/app/helmrelease.yaml
https://github.com/VictoriaMetrics/helm-charts/issues/2420
> fix: downgrade vm-operator chart
